"""
Django settings for isu_nstp_backend project.

Generated by 'django-admin startproject' using Django 5.2.15.
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-gu2))m0)ews2ontq1^thze6%10d0s7volvmath#-t)x=8v*$aw')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',') if os.getenv('ALLOWED_HOSTS') else ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'attendance',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Stands in for a cron job: sends due presence pings on API traffic.
    'attendance.middleware.PresenceDispatchMiddleware',
]

ROOT_URLCONF = 'isu_nstp_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'isu_nstp_backend.wsgi.application'


# Database configuration
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Production (Render) must supply a PostgreSQL DATABASE_URL. Locally, where
# DATABASE_URL is unset or holds an unsupported scheme (e.g. a Prisma shadow
# DB URL), we fall back to the existing local MySQL database so development
# keeps working unchanged. In production a missing/invalid DATABASE_URL is a
# hard error - never silently point at a local database.

from django.core.exceptions import ImproperlyConfigured

_LOCAL_DB_URL = 'mysql://root:096161@127.0.0.1:3306/isu_nstp_db'
_DATABASE_URL = os.getenv('DATABASE_URL')

try:
    DATABASES = {
        'default': dj_database_url.config(
            default=_LOCAL_DB_URL if _DATABASE_URL is None else _DATABASE_URL,
            conn_max_age=600,
            ssl_require=os.getenv('DATABASE_SSL_REQUIRE', 'false') == 'true',
        )
    }
except ValueError:
    if not DEBUG:
        raise ImproperlyConfigured(
            'DATABASE_URL is set to an unsupported value. '
            'Provide a valid PostgreSQL URL, e.g. '
            'postgresql://user:password@host:5432/dbname'
        )
    DATABASES = {
        'default': dj_database_url.parse(_LOCAL_DB_URL, conn_max_age=600)
    }

if _DATABASE_URL is None and not DEBUG:
    raise ImproperlyConfigured(
        'DATABASE_URL is required in production. Set it in Render -> Environment.'
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization & Timezone (Set to Philippine Standard Time)
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static and Media files (CSS, JavaScript, Uploaded Student IDs/Selfies)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ------------------------------------------------------------------------------
# FILE STORAGE
# ------------------------------------------------------------------------------
# Django 5.2 configures storage backends via the STORAGES dict. Static files
# are compressed + hashed by WhiteNoise and served from the same origin.

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Local development keeps files on disk (media/). When USE_SUPABASE_STORAGE is
# 'true' (production), uploaded files - student IDs, selfies, excuses - are
# stored in a Supabase Storage bucket (S3-compatible) so they survive Render's
# ephemeral disk / redeploys.
#
# Required env vars in production:
#   USE_SUPABASE_STORAGE=true
#   SUPABASE_S3_ACCESS_KEY   (Settings -> Storage -> S3 Access Keys)
#   SUPABASE_S3_SECRET_KEY
#   SUPABASE_S3_BUCKET       (e.g. "media", created as Public)
#   SUPABASE_S3_ENDPOINT_URL (https://<project-ref>.supabase.co/storage/v1/s3)
#   SUPABASE_S3_REGION       (e.g. ap-southeast-1)

if os.getenv('USE_SUPABASE_STORAGE', 'false') == 'true':
    INSTALLED_APPS += ['storages']
    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            'access_key': os.getenv('SUPABASE_S3_ACCESS_KEY', ''),
            'secret_key': os.getenv('SUPABASE_S3_SECRET_KEY', ''),
            'bucket_name': os.getenv('SUPABASE_S3_BUCKET', 'media'),
            'endpoint_url': os.getenv('SUPABASE_S3_ENDPOINT_URL', ''),
            'region_name': os.getenv('SUPABASE_S3_REGION', 'ap-southeast-1'),
            'file_overwrite': False,
            'querystring_auth': False,
            'default_acl': 'public-read',
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Set custom user model from attendance app
AUTH_USER_MODEL = 'attendance.User'


# ------------------------------------------------------------------------------
# EMAIL CONFIGURATION (Gmail SMTP)
# ------------------------------------------------------------------------------

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Load strictly from .env file
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

# Default display name and sender email
DEFAULT_FROM_EMAIL = f'ISU NSTP Support <{EMAIL_HOST_USER}>' if EMAIL_HOST_USER else 'ISU NSTP Support'

# Force Django to save cache/OTPs to disk so all threads share it
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': BASE_DIR / 'django_cache',
    }
}