# Generated by Django 5.2.15 on 2026-06-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_latitude', models.FloatField(default=16.924)),
                ('target_longitude', models.FloatField(default=121.7516)),
                ('allowed_radius_meters', models.IntegerField(default=100)),
                ('academic_year', models.CharField(default='2026-2027', max_length=20)),
                ('semester', models.CharField(default='1st Semester', max_length=20)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
