# Generated by Django 5.2.15 on 2026-07-28 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancerecord_mode_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='course_and_section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='id_picture_front',
            field=models.ImageField(blank=True, null=True, upload_to='student_ids/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_approved_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='component',
            field=models.CharField(blank=True, choices=[('CWTS', 'CWTS'), ('LTS', 'LTS'), ('ROTC', 'ROTC')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course_and_section',  # <-- Add the missing name parameter here
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
