# Generated by Django 5.2.15 on 2026-07-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingApproval',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Approval',
                'verbose_name_plural': 'Pending Approvals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('attendance.studentprofile',),
        ),
    ]
