# Generated by Django 5.2.15 on 2026-07-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_pendingapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
