# Generated by Django 5.2.15 on 2026-07-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_studentprofile_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='course_and_section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='section_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
