# Generated by Django 5.2.15 on 2026-07-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_studentprofile_course_and_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
