# Generated by Django 5.2.15 on 2026-07-31 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_studentprofile_fcm_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('component', models.CharField(blank=True, choices=[('CWTS', 'CWTS'), ('LTS', 'LTS'), ('ROTC', 'ROTC')], max_length=10, null=True)),
                ('section_code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('join_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('invite_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_join_enabled', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Approval'), ('removed', 'Removed')], default='active', max_length=10)),
                ('join_method', models.CharField(choices=[('code', 'Join Code'), ('link', 'Invitation Link'), ('manual', 'Added by Instructor')], default='code', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to='attendance.studentprofile')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='attendance.classgroup')),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('class_group', 'student')},
            },
        ),
    ]
