# Generated by Django 5.2.16 on 2026-08-01 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='attendance/checkout/'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='missed_checks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='presence_status',
            field=models.CharField(choices=[('ok', 'Verified Present'), ('warned', 'Warned - Missed A Check'), ('failed', 'Failed Verification')], default='ok', max_length=10),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='photo_window_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='presence_check_count',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='presence_response_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='PresenceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Scheduled'), ('sent', 'Awaiting Response'), ('responded', 'Responded'), ('missed', 'Missed')], default='pending', max_length=10)),
                ('response_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('response_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('was_warning', models.BooleanField(default=False)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_checks', to='attendance.attendancerecord')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
    ]
