# Generated by Django 5.2.15 on 2026-08-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_attendancerecord_check_out_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='check_out_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='is_check_out_open',
            field=models.BooleanField(default=False),
        ),
    ]
