# Generated by Django 5.2.16 on 2026-08-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_user_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=240),
        ),
    ]
