# Generated by Django 5.2.15 on 2026-08-08 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_alter_attendancesession_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Excused', 'Excused')], default='Absent', max_length=10),
        ),
        migrations.CreateModel(
            name='AttendanceExcuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('missed_check', 'Missed Presence Check'), ('absent', 'Did Not Time In')], max_length=15)),
                ('reason', models.TextField()),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='attendance/excuses/')),
                ('status', models.CharField(choices=[('pending', 'Awaiting Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('response_note', models.TextField(blank=True, null=True)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excuses', to='attendance.attendancerecord')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_excuses', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excuses', to='attendance.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excuses', to='attendance.studentprofile')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
