# Generated by Django 5.2.15 on 2026-08-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_alter_attendancerecord_status_attendanceexcuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='reminder_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='start_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
