# Generated by Django 5.2.16 on 2026-08-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_attendancesession_reminder_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='face_similarity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
