# Generated by Django 5.2.15 on 2026-08-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_attendancerecord_face_similarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceexcuse',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attendance/excuses/'),
        ),
    ]
