# Generated by Django 5.2.16 on 2026-09-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_geofence_leave_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceexcuse',
            name='kind',
            field=models.CharField(choices=[('missed_check', 'Missed Presence Check'), ('absent', 'Did Not Time In'), ('future_absence', 'Will Not Attend')], max_length=15),
        ),
    ]
