# Generated by Django 5.2.16 on 2026-09-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_excuse_future_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencecheck',
            name='response_photo',
            field=models.ImageField(blank=True, null=True, upload_to='presence_checks/'),
        ),
    ]
