# Generated by Django 5.2.16 on 2026-09-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_accountdeletionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_privacy_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
