# Generated by Django 5.2.16 on 2026-09-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0027_user_accepted_privacy_at_user_accepted_terms_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
