# Generated by Django 5.2.16 on 2026-09-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_alter_otpverification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
