# Generated by Django 5.2.16 on 2026-09-13 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_instructorprofile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
