# Generated by Django 5.2.16 on 2026-09-13 15:07

from django.db import migrations, models
from django.db.models import Count


def remove_duplicate_attendance_records(apps, schema_editor):
    """Collapse the duplicate rows the check-in race could have created.

    One row per (session, student) is the intent, but two concurrent time-ins
    could slip past the application-level check and both insert. Keep the
    earliest time-in (then the lowest id) and delete the rest. The deleted
    duplicates take their PresenceChecks and leave requests with them; any
    excuse that pointed at one has its `record` FK nulled (SET_NULL).
    """
    AttendanceRecord = apps.get_model('attendance', 'AttendanceRecord')

    duplicates = (
        AttendanceRecord.objects.values('session_id', 'student_id')
        .annotate(n=Count('id'))
        .filter(n__gt=1)
        .iterator()
    )

    for group in duplicates:
        rows = list(
            AttendanceRecord.objects
            .filter(
                session_id=group['session_id'],
                student_id=group['student_id'],
            )
            .order_by('timestamp', 'id')
        )
        # First row survives; the rest are artifacts of the race.
        for extra in rows[1:]:
            extra.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_attendancesession_cancelled_at_and_more'),
    ]

    operations = [
        migrations.RunPython(
            remove_duplicate_attendance_records,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='uniq_attendance_record_per_session'),
        ),
    ]
